config/routes.rb
Rails.application.routes.draw do
  #mount Motor::Admin => '/admin'
  root "home#index"
  devise_for :users
  
  resources :gauges do
    resources :measurements do
      resource :review, only: [:new, :create]
    end
  end
  
end

app/models/ability.rb
# frozen_string_literal: true
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'Editor'
      can :manage, PowerGauge, user_id: user.id
      can :manage, Measurement
    else
      can :read, PowerGauge
      can :read, Review
    end

    if user.role == 'Manager'
      can :manage, Review
      can :read, Measurement
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/measurement.rb
class Measurement < ApplicationRecord
    belongs_to :power_gauge
    has_one    :review, dependent: :destroy
    validates  :amount, presence: true, numericality: true
end

app/models/motor/ability.rb
# frozen_string_literal: true
class Motor::Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'Editor'
      can :manage, PowerGauge, user_id: user.id
    else
      can :read, PowerGauge
    end

    if user.role == 'Manager'
      can :manage, Review
    end
  end
end

app/models/power_gauge.rb
class PowerGauge < ApplicationRecord
    belongs_to :user
    has_many   :measurements, dependent: :destroy

    validates :name, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :unit, presence: true
    validates :time_unit, presence: true, inclusion: { in: ['days', 'weeks', 'months', 'years'] }
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :measurement
    
    validates :status, presence: true, inclusion: { in: ['Pending', 'Approved', 'Rejected'] }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :power_gauges, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  validates :role, presence: true, inclusion: { in: ['Editor', 'Manager'] }

  def is_manager?
    self.role == "Manager"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def after_sign_in_path_for(user)
        gauges_path
    end
    
end

app/controllers/gauges_controller.rb
class GaugesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_power_gauge, only: [:show]

    def index
      if current_user.is_manager?
        @power_gauges = PowerGauge.all
      else
        @power_gauges = current_user.power_gauges.all
      end
    end

    def new
      @gauge = PowerGauge.new
    end

    def show
      @measurement = @power_gauge.measurements 
    end    

    def create
      @gauge = current_user.power_gauges.new(gauge_params)
      if @gauge.save
        redirect_to new_gauge_measurement_path(@gauge)
      else
        render :new
      end
    end
  
    
    private
  
    def gauge_params
      params.require(:power_gauge).permit(:name, :start_date, :end_date, :unit, :time_unit)
    end

    def set_power_gauge
      if current_user.is_manager?
        @power_gauge = PowerGauge.find(params[:id])
      else
        @power_gauge = current_user.power_gauges.find(params[:id])
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to gauges_path if current_user
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    before_action :set_power_gauge
    before_action :set_measurement, only: [:show, :edit, :update]

    def index
      @measurements = @gauge.measurements.all
    end

    def new
      @measurement = @gauge.measurements.new
    end

    def show  
    end

    def edit
      if @measurement.review
        redirect_to gauge_url(@gauge) if @measurement.review.status == "Approved"
      else  
        redirect_to gauge_url(@gauge)
      end
    end

    def update
      if @measurement.update(measurement_params)
        @measurement.review.update(status: "Pending")
        redirect_to gauge_url(@gauge)
      else
        render :edit
      end
    end

    def create
      @measurement = @gauge.measurements.create(measurement_params)
      if @measurement.save
        redirect_to gauge_url(@gauge)
      else
        render :new
      end
    end
  
    
    
    private
  
    def measurement_params
      params.require(:measurement).permit(:amount)
    end

    def set_power_gauge
      @gauge = PowerGauge.find(params[:gauge_id])
    end

    def set_measurement
      @measurement = Measurement.find(params[:id])
    end
    
  
  end

app/controllers/reviews_controller.rb
# app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    before_action :set_power_gauge, :set_measurement

    def new
      @review = @measurement.build_review
    end
  
    def create
      @review = @measurement.build_review(review_params)
      @review.user = current_user
      
      if @review.save
        redirect_to gauge_path(@power_gauge)
      else
        render 'new'
      end
    end
  
    private
  
    def set_power_gauge
      @power_gauge = PowerGauge.find(params[:gauge_id])
    end

    def set_measurement
      @measurement = Measurement.find(params[:measurement_id])
    end
  
    def review_params
      params.require(:review).permit(:status)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper

    def display_navbar?
        return true unless controller_name == 'home' || controller_name == 'sessions'
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gauges/index.html.erb
<div class="container">

  <h1 class="mt-4 mb-4">Power Gauges</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Unit</th>
        <th scope="col">Time Unit</th>
      </tr>
    </thead>
    <tbody>
      <% @power_gauges.each do |power_gauge| %>
        <tr>
          <th scope="row"><%= power_gauge.id %></th>
          <td>
            <%= link_to gauge_path(power_gauge.id) do %>
                <p><%= power_gauge.name %><p>
            <% end %>
          </td>
          <td><%= power_gauge.start_date %></td>
          <td><%= power_gauge.end_date %></td>
          <td><%= power_gauge.unit %></td>
          <td><%= power_gauge.time_unit %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if !current_user.is_manager? %>
    <%= link_to 'Add New Gauge', new_gauge_path(), class: 'btn btn-primary mt-4' %>
  <% end %>

</div>

app/views/gauges/new.html.erb
<div class="container">
  <%= form_for @gauge, url: gauges_path, html: {class: "row g-3"} do |f| %>

    <div class="col-12">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= f.label :start_date, class: "form-label" %>
      <%= f.date_field :start_date, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= f.label :end_date, class: "form-label" %>
      <%= f.date_field :end_date, class: "form-control" %>
    </div>

    <div class="col-12">
      <%= f.label :unit, class: "form-label" %>
      <%= f.text_field :unit, class: "form-control" %>
    </div>

    <div class="col-12">
      <%= f.label :time_unit, class: "form-label" %>
      <%= f.select :time_unit, options_for_select(['days', 'weeks', 'months', 'years']), {}, {class: "form-select"} %>
    </div>

    <div class="col-12">
      <%= f.submit "Create Gauge", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/gauges/show.html.erb
<div class="container">

  <div class="jumbotron mt-4 mb-4">
    <h1 class="display-4"><%= @power_gauge.name %></h1>
  </div>

  <div class="card mb-4">
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9"><%= @power_gauge.name %></dd>

        <dt class="col-sm-3">Start Date</dt>
        <dd class="col-sm-9"><%= @power_gauge.start_date %></dd>

        <dt class="col-sm-3">End Date</dt>
        <dd class="col-sm-9"><%= @power_gauge.end_date %></dd>

        <dt class="col-sm-3">Unit</dt>
        <dd class="col-sm-9"><%= @power_gauge.unit %></dd>

        <dt class="col-sm-3">Time Unit</dt>
        <dd class="col-sm-9"><%= @power_gauge.time_unit %></dd>
      </dl>
    </div>
  </div>

  <hr>

  <h1 class="mt-4 mb-4">Measurements</h1>

  <div class="card mb-4">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @power_gauge.measurements.each do |m| %>
            <tr>
              <td><%= link_to "#{m.id}", gauge_measurement_path(id: m.id, gauge_id: m.power_gauge_id), class: 'btn btn-primary' %></td>
              <td><%= m.amount %></td>
              <% if m.review.present? %>
                <td><%= m.review.status %></td>  
              <% else %>
                <td>Pending</td>  
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to 'Back to Power Gauges', gauges_path, class: 'btn btn-primary mt-4' %>

</div>

app/views/home/index.html.erb
  <div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-6 text-center">
        <br/>
        <h1>Power Tech</h1>
        <%= image_tag 'download.png', class: 'img-fluid' %>
        <div class="mt-3">
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>PowerTech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if display_navbar? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><%= image_tag 'download.png', class: 'img-fluid', size: "50x50" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <% if current_user %>
              <div class="nav-item nav-link">Role: <%= current_user.role %></div>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
            <% else %>
              <%= link_to 'Login', new_user_session_path, class: 'nav-item nav-link' %>
            <% end %>
          </div>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/measurements/edit.html.erb
<div class="d-flex justify-content-center align-items-center vh-100">
  <div class="card">
    <div class="card-body">
      <%= form_for [@gauge, @measurement], url: gauge_measurement_path, html: { class: 'mx-auto' } do |f| %>
        <div class="form-group">
          <%= f.label :value, "Enter reading in #{@gauge.time_unit}", class: 'control-label' %>
          <%= f.number_field :amount, class: 'form-control' %>
        </div>
        <%= f.submit "Update Measurement", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/measurements/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card mt-5 mb-4 shadow-lg">
        <div class="card-header bg-primary text-white text-center">
          <h2 class="mb-0"><%= @gauge.name %></h2>
        </div>
        <div class="card-body">
          <% @measurements.each do |m| %>
            <%= link_to gauge_measurement_path(id: m.id), class: 'list-group-item list-group-item-action' do %>
              <h5 class="mb-0">Measurement: <%= m.id %> - <%= m.amount %></h5>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer text-center">
          <%= link_to 'Back to Power Gauges', gauges_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/measurements/new.html.erb
<br />
<div class="d-flex justify-content-center align-items-center vh-100">
  <div class="card">
    <div class="card-body">
      <%= form_for [@gauge, @measurement], url: gauge_measurements_path, html: { class: 'mx-auto' } do |f| %>
        <div class="form-group">
          <%= f.label :amount, "Enter reading", class: 'control-label' %>
          <%= f.number_field :amount, step: 'any', class: 'form-control' %>
        </div>

        <%= f.submit "Create Measurement", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/measurements/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card mt-5 mb-4 shadow-lg">
        <div class="card-header bg-primary text-white text-center">
          <h2 class="mb-0">Measurement: <%= @measurement.id %></h2>
        </div>
        <div class="card-body">
          <table class="table table-striped table-bordered">
            <thead class="table-dark">
              <tr>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @measurement.amount %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="card-footer text-center">
          <%= link_to 'Back to PowerGauge', gauge_path(id: @measurement.power_gauge_id), class: 'btn btn-secondary' %>
          <% if !current_user.is_manager? %>
            <% if @measurement.review %>
              <% if @measurement.review.status != "Approved" %>
                <%= link_to 'Edit', edit_gauge_measurement_path(measurement_id: @measurement.id), class: 'btn btn-success ms-2' %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to 'Review', new_gauge_measurement_review_path(measurement_id: @measurement.id), class: 'btn btn-success ms-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<!-- app/views/reviews/_form.html.erb -->
<%= form_for review, url: gauge_measurement_review_path do |f| %>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, [['Pending', 'Pending'], ['Approved', "Approved"], ['Rejected', "Rejected"]], {}, {class: 'form-control'} %>
  </div>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<div class="container h-100">
  <div class="row justify-content-center align-items-center">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center">Create New Review</h2>
          <%= render 'form', review: @review %>
        </div>
      </div>
    </div>
  </div>
</div>